### PR TITLE
Add Targeting behavior

### PR DESCRIPTION
**Pull request by askneller**
Adds components and behaviors related to targeting and visually following the character.

To test you can create a `curiousDeer.prefab` in Wild Animals:
```
{
  "skeletalmesh" : {
    "mesh" : "deer",
    "heightOffset" : -0.8,
    "material" : "deerSkin",
    "animation" : "deerIdle",
    "loop" : true
  },
  "Behavior" : {
    "tree" : "Behaviors:curiousCritter"
  },
  "FindNearbyPlayers": {
    "searchRadius" : 8
  },
  "BlockDropGrammar": {
    "blockDrops": [],
    "itemDrops": ["2*WildAnimals:meat"]
  },
  "Stand" :{
    "animationPool": [
      "deerIdle",
      "deerIdle",
      "deerIdle",
      "deerIdleLookLeft",
      "deerIdleLookRight",
      "deerIdleMoveLegs"
    ]
  },
  "Walk" :{
    "animationPool": ["deerWalk"]
  },
  "Die" :{
    "animationPool": ["deerFall"]
  },
  "MeleeAttack": {
    "animationPool": ["deerIdleMoveLegs"]
  },
  "persisted" : true,
  "location" : {},
  "Character" : {},
  "AliveCharacter": {},
  "WildAnimal" : {
    "name": "Deer",
    "icon": "WildAnimals:deerIcon"
  },
  "NPCMovement" : {},
  "CreatureNameGenerator" : {
    "genderRatio" : 0,
    "nobility" : 0,
    "theme": "ANIMAL"
  },
  "CharacterMovement" : {
    "groundFriction" : 16,
    "speedMultiplier" : 0.3,
    "distanceBetweenFootsteps" : 0.2,
    "distanceBetweenSwimStrokes" : 2.5,
    "height" : 1.6,
    "radius" : 0.3,
    "jumpSpeed" : 12
  },
  "CharacterSound" : {
    "footstepSounds" : ["FootGrass1", "FootGrass2", "FootGrass3", "FootGrass4", "FootGrass5"],
    "footstepVolume" : 0.03
  },
  "Network" :{},
  "MinionMove" : {},
  "Health" : {
    "destroyEntityOnNoHealth" : true,
    "currentHealth": 50,
    "maxHealth": 50
  },
  "BoxShape" : {
    "extents" : [1.5, 1.5, 1.5]
  },
  "Trigger" : {
    "detectGroups" : ["engine:debris", "engine:sensor"]
  }
}
```

When you get within 10 blocks it will turn to face you. You can circle around it and it will track you. If you move far enough away it will resume straying.

### CODE REVIEW

**Comment by casals** [comment]
Created a curiousDeer.prefab to run side-by-side with a (stable) deer; while the deer behaves as expected, the curiousDeer remains still (no animation/observable behavior whatsoever). Tried modifying the existing deer.prefab just in case - same thing. This usually happens when the behavior is not well-stuctured. Could you please check it?

**Comment by askneller** [comment]
Hi @casals thanks for the review. Can I ask for clarification, so the ```curiousDeer``` did nothing at all? It didn't turn to face you no matter how close you got?

**Comment by casals** [comment]
Hi @askneller - exactly. It's as if there was no behavior at all.

**Comment by askneller** [comment]
Hi @casals  I think it may have had something to do with a version number change I made to Behaviors. I've reversed that so that it's still at 0.2.2. Would you mind trying again please?

**Comment by askneller** [comment]
Also a note I had some troubles running the module after switching branches. The system wasn't recognizing the Behaviors module actions. I had to do a full ```gradlew buildNeeded``` after switching branches to get it working.

**Comment by casals** [comment]
Hi @askneller - the behavior is being loaded now (the "stray" part is working), but the deer doesn't look at me when I get close. It seems to turn into my general direction if I'm close when the straying stops, but it is not exact - most of the times, if the deer is moving away from me, for example, when it stops it changes its direction to look at my right (not directly at me).

**Comment by askneller** [comment]
Hi @casals  Would you be able to provide some screenshots of what you are experiencing if it's not too much trouble? I'm having trouble replicating. The deer won't always look _precisely_ at you, but will turn to face you to within a few degrees (currently 5).

**Comment by casals** [comment]
Actually I made a video, I think it's better for this case - sorry about the size, I don't really have anything to compress it right now. I changed the deer prefab to use the curiousCritter behavior. Please find it here: https://mega.nz/#F!AF9xQbIB!mh93ma4Be2L889rSOI4dxA

**Comment by askneller** [comment]
Ah, I see what it is. Sorry my bad. The creature prefab has to have the ```FindNearbyPlayers``` component. The one in ```curiousDeer``` for example was 
```
  "FindNearbyPlayers": {
    "searchRadius" : 8
  }
```
Sorry I should have pointed that out somewhere, the ```curiousCritter``` behavior has a guard on it:
```
guard: {
          componentPresent: "Behaviors:FindNearbyPlayers",
          values: ["N charactersWithinRange nonEmpty"],
          child: {
``` 
If you add ```FindNearbyPlayers``` to deer when you set its behavior then it should work (hopefully).

**Comment by casals** [comment]
OK - now I can confirm it's working as intended - nice! 
I just reviewed the other files - it seems that src/main/java/org/terasology/minion/move/LookAtAction.java is very well-documented, but that's not the case for most of the other Java files. Could you please add some documentation to them? The idea it to make it easy for someone to understand the code right away - especialy someone that's not familiar with the rest of the code (so comments like "this is used for that in that case" are very appreciated).

**Pull request merged**
